function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // par_building
	global.__objectDepths[1] = 100; // par_block
	global.__objectDepths[2] = 110; // par_wall
	global.__objectDepths[3] = 0; // par_deco
	global.__objectDepths[4] = 0; // obj_server
	global.__objectDepths[5] = 0; // obj_player
	global.__objectDepths[6] = 0; // obj_other_player
	global.__objectDepths[7] = -100000; // obj_notification
	global.__objectDepths[8] = 0; // obj_inventory
	global.__objectDepths[9] = 0; // obj_world
	global.__objectDepths[10] = 1000000; // obj_background
	global.__objectDepths[11] = 0; // obj_chat
	global.__objectDepths[12] = 105; // obj_gui
	global.__objectDepths[13] = -100000; // obj_options
	global.__objectDepths[14] = 0; // obj_banner
	global.__objectDepths[15] = 0; // obj_pan
	global.__objectDepths[16] = 0; // obj_music
	global.__objectDepths[17] = 0; // obj_trade
	global.__objectDepths[18] = 0; // obj_delete
	global.__objectDepths[19] = -100; // obj_button_login
	global.__objectDepths[20] = -100; // obj_button_planet
	global.__objectDepths[21] = -100; // obj_button_fuse
	global.__objectDepths[22] = 0; // obj_checkbox_no_account
	global.__objectDepths[23] = 100; // obj_form_login
	global.__objectDepths[24] = 0; // obj_form_fuse
	global.__objectDepths[25] = 0; // obj_form_planets
	global.__objectDepths[26] = 0; // obj_friends
	global.__objectDepths[27] = 0; // obj_form_skins
	global.__objectDepths[28] = 0; // obj_textbox_username
	global.__objectDepths[29] = 0; // obj_textbox_password
	global.__objectDepths[30] = 0; // obj_textbox_email
	global.__objectDepths[31] = 0; // obj_textbox_planet
	global.__objectDepths[32] = 0; // obj_placed
	global.__objectDepths[33] = 0; // obj_gem
	global.__objectDepths[34] = 0; // obj_chicken
	global.__objectDepths[35] = -100; // obj_slot_1
	global.__objectDepths[36] = -100; // obj_slot_2
	global.__objectDepths[37] = -100; // obj_handle
	global.__objectDepths[38] = -1530494977; // obj_interstitial
	global.__objectDepths[39] = 0; // obj_shop_planet_lock
	global.__objectDepths[40] = 0; // obj_shop_dice_block
	global.__objectDepths[41] = 0; // obj_shop_access_door
	global.__objectDepths[42] = 0; // obj_shop_golden_block
	global.__objectDepths[43] = 0; // obj_shop_platform
	global.__objectDepths[44] = 0; // obj_shop_checkpoint
	global.__objectDepths[45] = 0; // obj_shop_race_start_flag
	global.__objectDepths[46] = 0; // obj_shop_race_end_flag
	global.__objectDepths[47] = 0; // obj_shop_buzzsaw
	global.__objectDepths[48] = -100; // obj_skin_brown
	global.__objectDepths[49] = -100; // obj_skin_default
	global.__objectDepths[50] = -100; // obj_skin_white
	global.__objectDepths[51] = -100; // obj_skin_invisible
	global.__objectDepths[52] = -100; // obj_skin_ghost
	global.__objectDepths[53] = 0; // obj_block_00
	global.__objectDepths[54] = 100; // obj_block_qq
	global.__objectDepths[55] = 100; // obj_block_qw
	global.__objectDepths[56] = 100; // obj_block_qe
	global.__objectDepths[57] = 100; // obj_block_qr
	global.__objectDepths[58] = 100; // obj_block_qt
	global.__objectDepths[59] = 100; // obj_block_qy
	global.__objectDepths[60] = 100; // obj_block_qu
	global.__objectDepths[61] = 100; // obj_block_qi
	global.__objectDepths[62] = 100; // obj_block_qo
	global.__objectDepths[63] = 100; // obj_block_qp
	global.__objectDepths[64] = 100; // obj_block_qa
	global.__objectDepths[65] = 100; // obj_block_qs
	global.__objectDepths[66] = 100; // obj_block_qd
	global.__objectDepths[67] = 100; // obj_block_qf
	global.__objectDepths[68] = 100; // obj_block_qg
	global.__objectDepths[69] = 100; // obj_block_qh
	global.__objectDepths[70] = 100; // obj_block_qj
	global.__objectDepths[71] = 10; // obj_block_qk
	global.__objectDepths[72] = 100; // obj_block_ql
	global.__objectDepths[73] = 100; // obj_block_qz
	global.__objectDepths[74] = 100; // obj_block_qx
	global.__objectDepths[75] = 100; // obj_block_qc
	global.__objectDepths[76] = 100; // obj_block_qv
	global.__objectDepths[77] = 100; // obj_block_qb
	global.__objectDepths[78] = 100; // obj_block_qn
	global.__objectDepths[79] = 100; // obj_block_qm
	global.__objectDepths[80] = 100; // obj_block_wq
	global.__objectDepths[81] = 100; // obj_block_ww
	global.__objectDepths[82] = 100; // obj_block_we
	global.__objectDepths[83] = 100; // obj_block_wr
	global.__objectDepths[84] = 100; // obj_block_wt
	global.__objectDepths[85] = 100; // obj_block_wy
	global.__objectDepths[86] = 100; // obj_block_wu
	global.__objectDepths[87] = 100; // obj_block_wi
	global.__objectDepths[88] = 100; // obj_block_wo
	global.__objectDepths[89] = 100; // obj_block_wp
	global.__objectDepths[90] = 110; // obj_wall_q
	global.__objectDepths[91] = 110; // obj_wall_w
	global.__objectDepths[92] = 110; // obj_wall_e
	global.__objectDepths[93] = 110; // obj_wall_r
	global.__objectDepths[94] = 110; // obj_wall_t
	global.__objectDepths[95] = 110; // obj_wall_y
	global.__objectDepths[96] = 110; // obj_wall_u
	global.__objectDepths[97] = 110; // obj_wall_i
	global.__objectDepths[98] = 110; // obj_wall_o


	global.__objectNames[0] = "par_building";
	global.__objectNames[1] = "par_block";
	global.__objectNames[2] = "par_wall";
	global.__objectNames[3] = "par_deco";
	global.__objectNames[4] = "obj_server";
	global.__objectNames[5] = "obj_player";
	global.__objectNames[6] = "obj_other_player";
	global.__objectNames[7] = "obj_notification";
	global.__objectNames[8] = "obj_inventory";
	global.__objectNames[9] = "obj_world";
	global.__objectNames[10] = "obj_background";
	global.__objectNames[11] = "obj_chat";
	global.__objectNames[12] = "obj_gui";
	global.__objectNames[13] = "obj_options";
	global.__objectNames[14] = "obj_banner";
	global.__objectNames[15] = "obj_pan";
	global.__objectNames[16] = "obj_music";
	global.__objectNames[17] = "obj_trade";
	global.__objectNames[18] = "obj_delete";
	global.__objectNames[19] = "obj_button_login";
	global.__objectNames[20] = "obj_button_planet";
	global.__objectNames[21] = "obj_button_fuse";
	global.__objectNames[22] = "obj_checkbox_no_account";
	global.__objectNames[23] = "obj_form_login";
	global.__objectNames[24] = "obj_form_fuse";
	global.__objectNames[25] = "obj_form_planets";
	global.__objectNames[26] = "obj_friends";
	global.__objectNames[27] = "obj_form_skins";
	global.__objectNames[28] = "obj_textbox_username";
	global.__objectNames[29] = "obj_textbox_password";
	global.__objectNames[30] = "obj_textbox_email";
	global.__objectNames[31] = "obj_textbox_planet";
	global.__objectNames[32] = "obj_placed";
	global.__objectNames[33] = "obj_gem";
	global.__objectNames[34] = "obj_chicken";
	global.__objectNames[35] = "obj_slot_1";
	global.__objectNames[36] = "obj_slot_2";
	global.__objectNames[37] = "obj_handle";
	global.__objectNames[38] = "obj_interstitial";
	global.__objectNames[39] = "obj_shop_planet_lock";
	global.__objectNames[40] = "obj_shop_dice_block";
	global.__objectNames[41] = "obj_shop_access_door";
	global.__objectNames[42] = "obj_shop_golden_block";
	global.__objectNames[43] = "obj_shop_platform";
	global.__objectNames[44] = "obj_shop_checkpoint";
	global.__objectNames[45] = "obj_shop_race_start_flag";
	global.__objectNames[46] = "obj_shop_race_end_flag";
	global.__objectNames[47] = "obj_shop_buzzsaw";
	global.__objectNames[48] = "obj_skin_brown";
	global.__objectNames[49] = "obj_skin_default";
	global.__objectNames[50] = "obj_skin_white";
	global.__objectNames[51] = "obj_skin_invisible";
	global.__objectNames[52] = "obj_skin_ghost";
	global.__objectNames[53] = "obj_block_00";
	global.__objectNames[54] = "obj_block_qq";
	global.__objectNames[55] = "obj_block_qw";
	global.__objectNames[56] = "obj_block_qe";
	global.__objectNames[57] = "obj_block_qr";
	global.__objectNames[58] = "obj_block_qt";
	global.__objectNames[59] = "obj_block_qy";
	global.__objectNames[60] = "obj_block_qu";
	global.__objectNames[61] = "obj_block_qi";
	global.__objectNames[62] = "obj_block_qo";
	global.__objectNames[63] = "obj_block_qp";
	global.__objectNames[64] = "obj_block_qa";
	global.__objectNames[65] = "obj_block_qs";
	global.__objectNames[66] = "obj_block_qd";
	global.__objectNames[67] = "obj_block_qf";
	global.__objectNames[68] = "obj_block_qg";
	global.__objectNames[69] = "obj_block_qh";
	global.__objectNames[70] = "obj_block_qj";
	global.__objectNames[71] = "obj_block_qk";
	global.__objectNames[72] = "obj_block_ql";
	global.__objectNames[73] = "obj_block_qz";
	global.__objectNames[74] = "obj_block_qx";
	global.__objectNames[75] = "obj_block_qc";
	global.__objectNames[76] = "obj_block_qv";
	global.__objectNames[77] = "obj_block_qb";
	global.__objectNames[78] = "obj_block_qn";
	global.__objectNames[79] = "obj_block_qm";
	global.__objectNames[80] = "obj_block_wq";
	global.__objectNames[81] = "obj_block_ww";
	global.__objectNames[82] = "obj_block_we";
	global.__objectNames[83] = "obj_block_wr";
	global.__objectNames[84] = "obj_block_wt";
	global.__objectNames[85] = "obj_block_wy";
	global.__objectNames[86] = "obj_block_wu";
	global.__objectNames[87] = "obj_block_wi";
	global.__objectNames[88] = "obj_block_wo";
	global.__objectNames[89] = "obj_block_wp";
	global.__objectNames[90] = "obj_wall_q";
	global.__objectNames[91] = "obj_wall_w";
	global.__objectNames[92] = "obj_wall_e";
	global.__objectNames[93] = "obj_wall_r";
	global.__objectNames[94] = "obj_wall_t";
	global.__objectNames[95] = "obj_wall_y";
	global.__objectNames[96] = "obj_wall_u";
	global.__objectNames[97] = "obj_wall_i";
	global.__objectNames[98] = "obj_wall_o";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
